server:
  port: 8099

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/tanujkumarsaini/microservices-config
          clone-on-start: true