server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL8Dialect

  #
  #eureka:
  #  instance:
  #    prefer-ip-address: true
  #  client:
  #    fetch-registry: true
  #    register-with-eureka: true
  #    service-url:
  #      defaultZone: http://localhost:8761/eureka


  config:
    import: optional:configserver:http://localhost:8099


  application:
    name: USER-SERVICE

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-47458907.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa91xns93Wjzy1zQ5d7
            client-secret: y37_fLX7VoIwtpTo07vuZ-dLdXiFcX2hZWda19qb
        provider:
          okta:
            issuer-uri: https://dev-47458907.okta.com/oauth2/default



management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 8s
        limit-for-period: 2
        timeout-duration: 0s

okta:
  oauth2:
    issuer: https://dev-47458907.okta.com/oauth2/default
    audience: api://default